version: "2"
services:
    flink-master:
      image: bde2020/flink-master
      hostname: flink-master
      container_name: flink-master
      environment:
        - INIT_DAEMON_STEP=setup_flink
#     - "constraint:node==<yourmasternode>"
      ports:
       - "8080:8080"
       - "8081:8081"
    labels:
      - "logging=true"
    flink-worker:
      image: bde2020/flink-worker
      hostname: flink-worker
      container_name: flink-worker
      environment:
       - "FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master"
       - "constraint:node==<yourworkernode>"
      depends_on:
        - "flink-master"
      labels:
      - "logging=true"
    hive:
      image: bde2020/hive